# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoReleaserTest < Formula
  desc "The PlanetScale CLI"
  homepage "https://planetscale.com/"
  version "0.1.13"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/planetscale/go-releaser-test/releases/download/v0.1.13/go-releaser-test_0.1.13_macOS_amd64.tar.gz"
    sha256 "0552314a5cea39bfb3455469fc57d1d8201ac49018332dc3a98e1e49147c7b55"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/planetscale/go-releaser-test/releases/download/v0.1.13/go-releaser-test_0.1.13_linux_amd64.tar.gz"
    sha256 "b007a111fb2594dec81bec6545be3586c02f7ba06eb37f1a11d2d0ed0fe82680"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/planetscale/go-releaser-test/releases/download/v0.1.13/go-releaser-test_0.1.13_linux_arm64.tar.gz"
    sha256 "85a21e41a8ebd758f963803d18a1881a4a8792172602fb6891f290c2176c1383"
  end

  depends_on "mysql" => :optional

  def install
    bin.install "go-releaser-test"
  end

  test do
    system "#{bin}/ptest --version"
  end
end
