# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PsHttpTap < Formula
  desc "Singer.io HTTP Tap"
  homepage "https://planetscale.com/"
  version "0.26.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.26.0/ps-singer-tap_0.26.0_darwin_arm64.tar.gz"
      sha256 "8227cf208361910aef845e59bbcb751a6f8af0f6e7605d97dfcc1d3d304c9c39"

      def install
        bin.install "ps-http-tap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.26.0/ps-singer-tap_0.26.0_darwin_amd64.tar.gz"
      sha256 "21d89b42608e45da121b27c384e729fc45564f265ed102a1ad31189449fc3876"

      def install
        bin.install "ps-http-tap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.26.0/ps-singer-tap_0.26.0_linux_arm64.tar.gz"
      sha256 "8fad80cd3871275a5314b3521400ca29133f05ea46a804a2b8384690f6de1d1e"

      def install
        bin.install "ps-http-tap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.26.0/ps-singer-tap_0.26.0_linux_amd64.tar.gz"
      sha256 "b0137a6a9d288815901fa91df9fd6b535b3f79b2386639725eb00803706a9037"

      def install
        bin.install "ps-http-tap"
      end
    end
  end
end
