# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PsHttpTap < Formula
  desc "Singer.io HTTP Tap"
  homepage "https://planetscale.com/"
  version "0.8.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.8.0/ps-singer-tap_0.8.0_darwin_amd64.tar.gz"
      sha256 "ebdfdfa3712b877ac861ad6acfc34613f879e2534f0f516cd2df9f89a1f893ab"

      def install
        bin.install "ps-http-tap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.8.0/ps-singer-tap_0.8.0_darwin_arm64.tar.gz"
      sha256 "80a225ce4f1aa316d15a95d9d5da40c6a9ea56bbfa9889bc718cc156414a491b"

      def install
        bin.install "ps-http-tap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.8.0/ps-singer-tap_0.8.0_linux_armv6.tar.gz"
      sha256 "51c9d4e978b21c0ccb24b4eb722631ddadeed6d5ff8835d06cfb23e4741387ca"

      def install
        bin.install "ps-http-tap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.8.0/ps-singer-tap_0.8.0_linux_arm64.tar.gz"
      sha256 "a9f996b66d6fdca8874eb86af5c9d92c945fe37817a36383d3cc0c5eae5dcc76"

      def install
        bin.install "ps-http-tap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.8.0/ps-singer-tap_0.8.0_linux_amd64.tar.gz"
      sha256 "fd56e12ab374ba16cf8c6ed81561263915de155e1dbe56955646dd314c8c79ee"

      def install
        bin.install "ps-http-tap"
      end
    end
  end
end
