# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PsSingerTap < Formula
  desc "The PlanetScale Singer.io Tap"
  homepage "https://planetscale.com/"
  version "0.5.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.5.0/ps-singer-tap_0.5.0_darwin_arm64.tar.gz"
      sha256 "8a6411acf261935a0c53b0f0bd9d42d165a31b27a119d5a6d999c73037509b45"

      def install
        bin.install "ps-singer-tap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.5.0/ps-singer-tap_0.5.0_darwin_amd64.tar.gz"
      sha256 "c276733d12839725c62f3f4022b440aea173b6d74b8c865accef6efd76b2497c"

      def install
        bin.install "ps-singer-tap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.5.0/ps-singer-tap_0.5.0_linux_armv6.tar.gz"
      sha256 "b3e2ba0dcca3d5ab77e19705e9cbdaca6c02dfb2f656c1334d1a7ec7ada4bf49"

      def install
        bin.install "ps-singer-tap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.5.0/ps-singer-tap_0.5.0_linux_arm64.tar.gz"
      sha256 "578a0661984627180c0fc684390a3908dbb7de3adc04afb2b2c7cd6ccb777328"

      def install
        bin.install "ps-singer-tap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.5.0/ps-singer-tap_0.5.0_linux_amd64.tar.gz"
      sha256 "d2f2fdb4bc39c54623e61c87d796fccf247fe6ba07730893e9aa2ea72cc680fe"

      def install
        bin.install "ps-singer-tap"
      end
    end
  end
end
