# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PsSingerTap < Formula
  desc "The PlanetScale Singer.io Tap"
  homepage "https://planetscale.com/"
  version "0.9.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.9.0/ps-singer-tap_0.9.0_darwin_arm64.tar.gz"
      sha256 "5f05b69760b22b8f3ede1d34b247de0d3880f4bc72aed4a020060056740f1441"

      def install
        bin.install "ps-singer-tap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.9.0/ps-singer-tap_0.9.0_darwin_amd64.tar.gz"
      sha256 "0e318f4d048a6fbabd83795caace6da5cb8d35dd9583e0889e0a5c91de7481c0"

      def install
        bin.install "ps-singer-tap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.9.0/ps-singer-tap_0.9.0_linux_armv6.tar.gz"
      sha256 "531f47e157442525cd7d4bcbca31c6652be24ca16d5444f667d9798d08b1d191"

      def install
        bin.install "ps-singer-tap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.9.0/ps-singer-tap_0.9.0_linux_arm64.tar.gz"
      sha256 "c0f20e5053b57615cb8761cceb40f5076bc4941a66040ffb427366f3c72778ed"

      def install
        bin.install "ps-singer-tap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/planetscale/singer-tap/releases/download/v0.9.0/ps-singer-tap_0.9.0_linux_amd64.tar.gz"
      sha256 "22059efad8d05d72890b703f145ac112251a1f2d377177d93d479a04b6dd3c5d"

      def install
        bin.install "ps-singer-tap"
      end
    end
  end
end
