# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PscaleProxy < Formula
  desc "The PlanetScale SQL Proxy"
  homepage "https://planetscale.com/"
  version "0.10.0"
  license "Apache 2.0"
  bottle :unneeded

  on_macos do
    url "https://github.com/planetscale/sql-proxy/releases/download/v0.10.0/pscale-proxy_0.10.0_macOS_amd64.tar.gz"
    sha256 "cf4db92e1d8ed03bbb6dbedeee43295b1dfd73c45cc43d3eebc7c981cf5948b1"
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/planetscale/sql-proxy/releases/download/v0.10.0/pscale-proxy_0.10.0_linux_amd64.tar.gz"
      sha256 "11752fdbac0ba2d5384011472fb135a754a08b2f4a373ed2717e7c78f82ade0d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planetscale/sql-proxy/releases/download/v0.10.0/pscale-proxy_0.10.0_linux_arm64.tar.gz"
      sha256 "9c8cd9d52fca68b6dbd5ec607b4d4f6eaae2fcf6738a4a17231a0122938be709"
    end
  end

  def install
    bin.install "pscale-proxy"
  end

  test do
    system "#{bin}/pscale-proxy --version"
  end
end
