# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pscale < Formula
  desc "The PlanetScale CLI"
  homepage "https://planetscale.com/"
  version "0.303.0"
  license "Apache 2.0"

  depends_on "mysql" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/planetscale/cli/releases/download/v0.303.0/pscale_0.303.0_macOS_amd64.tar.gz"
      sha256 "9766cbd7d28b6a9c022918163b08ce1630e324f7a76927fa103c7f2c0ae038a3"

      define_method(:install) do
        bin.install "pscale"
        bash_completion.install "completions/pscale.bash" => "pscale"
        zsh_completion.install "completions/pscale.zsh" => "_pscale"
        fish_completion.install "completions/pscale.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/planetscale/cli/releases/download/v0.303.0/pscale_0.303.0_macOS_arm64.tar.gz"
      sha256 "95cba4233799b737a44fa0bb9cf91710aa01893228e1aac2fbad9d4ec08dca02"

      define_method(:install) do
        bin.install "pscale"
        bash_completion.install "completions/pscale.bash" => "pscale"
        zsh_completion.install "completions/pscale.zsh" => "_pscale"
        fish_completion.install "completions/pscale.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/planetscale/cli/releases/download/v0.303.0/pscale_0.303.0_linux_amd64.tar.gz"
      sha256 "54f777b74a694ee30af57c85fc430e121110a3a5b66b6a4ab1c5ac6d0b6ef4af"
      define_method(:install) do
        bin.install "pscale"
        bash_completion.install "completions/pscale.bash" => "pscale"
        zsh_completion.install "completions/pscale.zsh" => "_pscale"
        fish_completion.install "completions/pscale.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/planetscale/cli/releases/download/v0.303.0/pscale_0.303.0_linux_arm.tar.gz"
      sha256 "76509134517e3f516eb9dfa7ef8df7d802b3b6073b212318fe2a558fc8b28f33"
      define_method(:install) do
        bin.install "pscale"
        bash_completion.install "completions/pscale.bash" => "pscale"
        zsh_completion.install "completions/pscale.zsh" => "_pscale"
        fish_completion.install "completions/pscale.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/planetscale/cli/releases/download/v0.303.0/pscale_0.303.0_linux_arm64.tar.gz"
      sha256 "118d3d6b8b21259878b80635ac82250cbac72357f241619a24b079da861650d9"
      define_method(:install) do
        bin.install "pscale"
        bash_completion.install "completions/pscale.bash" => "pscale"
        zsh_completion.install "completions/pscale.zsh" => "_pscale"
        fish_completion.install "completions/pscale.fish"
      end
    end
  end

  test do
    system "#{bin}/pscale --version"
  end
end
