# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class PscaleProxy < Formula
  desc "The PlanetScale SQL Proxy"
  homepage "https://planetscale.com/"
  version "0.1.3"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/planetscale/sql-proxy/releases/download/v0.1.3/pscale-proxy_0.1.3_macOS_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "c205609fd6a4c6656fe1ebdd82d25023d1f3f490383cda2538e43565da6b244d"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/planetscale/sql-proxy/releases/download/v0.1.3/pscale-proxy_0.1.3_macOS_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "e41ee8b68f60595ff577a17dbec8da361ce4733f78d16f9590b3fbea1c193a68"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/planetscale/sql-proxy/releases/download/v0.1.3/pscale-proxy_0.1.3_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "e6cd1e352a5838b59b16b0bd97932695dfa2c185403e24a6c61ea3782eda33f9"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/planetscale/sql-proxy/releases/download/v0.1.3/pscale-proxy_0.1.3_linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "4236e75f003e7cf929e51c2dbf4d9cd7378cca53ca310af09fe42b27ac9a83d8"
  end

  def install
    bin.install "pscale-proxy"
  end

  test do
    system "#{bin}/pscale-proxy --version"
  end
end
