# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pscale < Formula
  desc "The PlanetScale CLI"
  homepage "https://planetscale.com/"
  version "0.50.0"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/planetscale/cli/releases/download/v0.50.0/pscale_0.50.0_macOS_amd64.tar.gz"
    sha256 "20a2ddf0995beb0ef28fdb9ea6a91bde3380004ae7dea178adb9baa0725cbc6d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/planetscale/cli/releases/download/v0.50.0/pscale_0.50.0_linux_amd64.tar.gz"
    sha256 "d7b663572f30435e6363cc9b5f7f6e20dd6eedfd8239dfeae9cc279725edc8d6"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/planetscale/cli/releases/download/v0.50.0/pscale_0.50.0_linux_arm64.tar.gz"
    sha256 "c0400c55940ba099a1dbd3ee78954e98e396e61c99a1dc6fd9c5473ac504cfc8"
  end

  depends_on "mysql" => :optional

  def install
    bin.install "pscale"
    bash_completion.install "completions/pscale.bash" => "pscale"
    zsh_completion.install "completions/pscale.zsh" => "_pscale"
    fish_completion.install "completions/pscale.fish"
  end

  test do
    system "#{bin}/pscale --version"
  end
end
