# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Pstest < Formula
  desc "The PlanetScale CLI"
  homepage "https://planetscale.com/"
  version "0.1.19"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/planetscale/go-releaser-test/releases/download/v0.1.19/go-releaser-test_0.1.19_macOS_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "b62ceba46586293d1013df855b2fd40bd5083e682a95a4c18bacfdaed3a45d54"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/planetscale/go-releaser-test/releases/download/v0.1.19/go-releaser-test_0.1.19_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "bd6f2a22d513489aadd689dcd9cffcc650c6e6195d5f26a636ce8b1f0f12539c"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/planetscale/go-releaser-test/releases/download/v0.1.19/go-releaser-test_0.1.19_linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "c8786866d32202e0097c10990843e816644a047aee435a2ed91c07eca2a48aca"
  end

  depends_on "mysql" => :optional

  def install
    bin.install "pstest"
  end

  test do
    system "#{bin}/pstest --version"
  end
end
