# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Pstest < Formula
  desc "The PlanetScale CLI"
  homepage "https://planetscale.com/"
  version "0.1.23"
  license "Apache 2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/planetscale/go-releaser-test/releases/download/v0.1.23/go-releaser-test_0.1.23_macOS_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "c4a535a2c6b01f2951d6b8912e3a95c610d77e582ecaecab4de8f13eeda9f187"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/planetscale/go-releaser-test/releases/download/v0.1.23/go-releaser-test_0.1.23_macOS_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "6935541d92d04349f2832eeb399404afeb50ec7fd52525524f871ab5ce632636"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/planetscale/go-releaser-test/releases/download/v0.1.23/go-releaser-test_0.1.23_linux_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "4df4f839f8df6d979aef3205a21c6eed5531c6543bf3a02be64ca00208634787"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/planetscale/go-releaser-test/releases/download/v0.1.23/go-releaser-test_0.1.23_linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "f40f3eb828b90e16225973bca2d5ea7c804eecf56f550a94c853f1d225d6a865"
  end

  depends_on "mysql" => :optional

  def install
    bin.install "pstest"
  end

  test do
    system "#{bin}/pstest --version"
  end
end
